export const siteData = {
  businessName: "Duval Plomberie",
  owner: "Laurent Duval",
  trade: "Plombier Chauffagiste",
  city: "Lyon",
  phone: "06 45 78 23 91",
  phoneHref: "tel:+33645782391",
  email: "contact@duval-plombier-lyon.fr",
  address: "47 rue de la République, 69002 Lyon",
  siret: "84523167900014",
  yearsExperience: 8,
  googleRating: 4.8,
  googleReviewCount: 87,
  hours: "Lun-Sam 7h-20h",
  emergency: "7j/7 24h/24",
  zone: "Lyon et agglomération 20km",
  colors: {
    primary: "#1E3A5F",
    secondary: "#F4F6F8",
    accent: "#3B82F6",
    dark: "#2D3436",
    white: "#FFFFFF",
  },
  business: {
    name: "Duval Plomberie",
    phone: "06 45 78 23 91",
    phoneLink: "tel:+33645782391",
    email: "contact@duval-plombier-lyon.fr",
    address: "47 rue de la République, 69002 Lyon",
    hours: "Lun-Sam 7h-20h",
    emergency: "7j/7 24h/24",
    experienceYears: 8,
    satisfaction: "4.8/5",
    interventions: "+2 500",
    tagline: "Votre plombier de confiance à Lyon — Réactif, transparent, efficace",
    description: "Plombier chauffagiste à Lyon depuis 8 ans. Dépannage urgence 7j/7, installation chaudières, rénovation salles de bain, détection de fuites.",
  },
  navigation: [
    { label: "Accueil", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Réalisations", href: "/gallery" },
    { label: "À propos", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  services: [
    {
      id: "urgence",
      title: "Dépannage urgence",
      description: "Intervention rapide en moins de 30 minutes sur Lyon et son agglomération. Fuites, canalisations bouchées, pannes de chaudière : nous intervenons 7j/7, 24h/24.",
      icon: "Clock",
      features: ["Disponible 7j/7, 24h/24", "Intervention en moins de 30 minutes", "Diagnostic immédiat sur place", "Devis avant intervention"],
    },
    {
      id: "chaudieres",
      title: "Installation chaudières",
      description: "Installation, remplacement et entretien de chaudières gaz, fioul et pompes à chaleur. Conseils personnalisés pour optimiser votre consommation énergétique.",
      icon: "Flame",
      features: ["Chaudières gaz et fioul", "Pompes à chaleur", "Entretien annuel obligatoire", "Conseils économies énergie"],
    },
    {
      id: "salles-de-bain",
      title: "Rénovation salles de bain",
      description: "Conception et réalisation complète de votre salle de bain. Du plan à la finition, nous créons un espace fonctionnel et esthétique adapté à vos envies.",
      icon: "Bath",
      features: ["Conception sur-mesure", "Douche à l'italienne", "Accessibilité PMR", "Finitions haut de gamme"],
    },
    {
      id: "fuites",
      title: "Détection de fuites",
      description: "Recherche et réparation de fuites avec des équipements professionnels de pointe. Détection non destructive pour préserver vos installations.",
      icon: "Droplet",
      features: ["Détection non destructive", "Caméra thermique", "Réparation immédiate", "Rapport détaillé"],
    },
    {
      id: "entretien",
      title: "Entretien plomberie",
      description: "Maintenance préventive et curative de vos installations. Contrats d'entretien annuel pour chaudières, détartrage et vérification complète de votre plomberie.",
      icon: "Wrench",
      features: ["Contrat annuel disponible", "Détartrage complet", "Vérification installations", "Prévention des pannes"],
    },
  ],
  testimonials: [
    {
      name: "Marc D.",
      city: "Lyon 3e",
      text: "Intervention ultra rapide pour une fuite en pleine nuit. Travail propre et soigné, tarif honnête. Je recommande vivement Laurent !",
      rating: 5,
    },
    {
      name: "Sophie L.",
      city: "Villeurbanne",
      text: "Rénovation complète de notre salle de bain. Le résultat est magnifique, dans les délais et le budget annoncé. Un vrai professionnel.",
      rating: 5,
    },
    {
      name: "Pierre M.",
      city: "Lyon 6e",
      text: "Remplacement de chaudière effectué rapidement et proprement. Laurent a pris le temps de tout nous expliquer. Très satisfaits.",
      rating: 5,
    },
    {
      name: "Catherine R.",
      city: "Caluire-et-Cuire",
      text: "Détection de fuite introuvable depuis des mois. Laurent a trouvé et réparé en une seule intervention. Merci pour votre expertise !",
      rating: 5,
    },
  ],
  gallery: [
    {
      title: "Salle de bain moderne",
      alt: "Rénovation complète salle de bain avec douche à l'italienne",
      description: "Rénovation complète avec douche à l'italienne",
      category: "Salles de bain",
      url: "/images/gallery/salle-de-bain-moderne.jpg",
    },
    {
      title: "Installation chaudière",
      alt: "Installation chaudière gaz à condensation",
      description: "Chaudière gaz à condensation haute performance",
      category: "Chaudières",
      url: "/images/gallery/installation-chaudiere.jpg",
    },
    {
      title: "Réparation urgente",
      alt: "Intervention rapide sur canalisation percée",
      description: "Intervention rapide sur canalisation percée",
      category: "Dépannage",
      url: "/images/gallery/reparation-urgente.jpg",
    },
    {
      title: "Salle de bain PMR",
      alt: "Aménagement salle de bain accessible PMR",
      description: "Aménagement accessible pour personnes à mobilité réduite",
      category: "Salles de bain",
      url: "/images/gallery/salle-de-bain-pmr.jpg",
    },
    {
      title: "Plomberie neuve",
      alt: "Installation plomberie complète appartement rénové",
      description: "Installation complète pour appartement rénové",
      category: "Plomberie",
      url: "/images/gallery/plomberie-neuve.jpg",
    },
    {
      title: "Détection de fuite",
      alt: "Détection de fuite avec équipement professionnel",
      description: "Localisation précise sans destruction grâce à nos équipements",
      category: "Dépannage",
      url: "/images/gallery/detection-fuite.jpg",
    },
  ],
} as const;

export type SiteData = typeof siteData;
